### PR TITLE
fix(xwayland): prevent use-after-free in xauth file path construction

### LINKED ISSUE #727: [Bug]:  treeland-xwayland asan crash
### SUMMARY | 问题概要

Reading symbols from /usr/libexec/treeland-xwayland...
[New LWP 1593]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/libexec/treeland-xwayland :0 -rootless -core -terminate -listenfd 70 -listenfd 71 -displayfd 88 -wm 85'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f6d8b75913c in ?? () from /usr/libexec/../lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007f6d8b75913c in ?? () from /usr/libexec/../lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f6d8b70b282 in raise () from /usr/libexec/../lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f6d8b6f44f2 in abort () from /usr/libexec/../lib/x86_64-linux-gnu/libc.so.6
#3  0x000055ff3d773d5b in __sanitizer::Abort() ()
#4  0x000055ff3d771e05 in __sanitizer::Die() ()
#5  0x000055ff3d75282f in __asan::ScopedInErrorReport::~ScopedInErrorReport() ()
#6  0x000055ff3d7558bd in __asan::ReportGenericError(unsigned long, unsigned long, unsigned long, unsigned long, bool, unsigned long, unsigned int, bool) ()
#7  0x000055ff3d710cea in __interceptor_fopen ()
#8  0x000055ff3d78e370 in main (argc=13, argv=0x7fff4629a898) at /home/uos/Downloads/treeland/src/xwayland.cpp:45
(gdb) quit

### LAUNCH-WAY | 启动方式

unknown

### BACKEND | 启动后端

unknown

### STEPS TO REPRODUCE | 复现步骤

重启ddm或者treeland服务必崩

### OBSERVED RESULT | 观察到的结果

_No response_

### EXPECTED RESULT | 期望的结果

_No response_

### ADDITIONAL INFORMATION | 额外补充

_No response_

### PR DESCRIPTION
**Pull request by zorowk**
Extend QString lifetime and use QByteArray to avoid dangling pointer in fopen. 

Issue: Fixes #727
Influence: restart ddm.service treeland.service

## Summary by Sourcery

Bug Fixes:
- Fix a potential use-after-free in XWayland xauth file path construction by ensuring the filename buffer remains valid during fopen().

## Summary by Sourcery

Bug Fixes:
- Ensure the xauth file path buffer remains valid for fopen() by storing it in a QByteArray instead of a temporary QString.

### CODE REVIEW

**Review by zccrs — CHANGES_REQUESTED** [review]

File: src/xwayland.cpp [hunk 1]
```diff
@@ -39,8 +39,9 @@ int main(int argc, char *argv[])
         cookie[i] = dis(gen);
 
     // Create xauth file
-    char *display = argv[1]; // display is passed as the first argument
-    const char *fileName = qPrintable(QStringLiteral("/tmp/.xauth_%1").arg(display));
+    QString display = QString::fromLocal8Bit(argv[1]); // display is passed as the first argument
```
Comment (zccrs) [inline src/xwayland.cpp]: 另外搞个commit，对这个display做个有效性验证，只能是个文件，不能是个路径，避免路径注入问题。

**Review by zccrs — CHANGES_REQUESTED** [review]
